# Generated by Django 2.1.15 on 2023-04-07 11:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('filmsapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='moviesactors',
            name='actors',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='filmsapi.Actors'),
        ),
        migrations.AlterField(
            model_name='moviesactors',
            name='movies',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='filmsapi.Movies'),
        ),
    ]
